@host = http://localhost:5263

### Get all jobs
GET {{host}}/api/jobs

###

### Get job by ID
GET {{host}}/api/jobs/1

###

### Get job that does not exist
GET {{host}}/api/jobs/999

###

### Create a job
POST {{host}}/api/jobs
Content-Type: application/json

{
  "title": "Junior .NET Developer",
  "company": "ABC Technologies",
  "location": "Addis Ababa",
  "jobType": "Full-time",
  "description": "We are looking for a junior .NET developer to join our development team.",
  "salary": 15000
}

###

### Update job
PUT {{host}}/api/jobs/1
Content-Type: application/json

{
  "title": "Senior .NET Developer",
  "company": "ABC Technologies",
  "location": "Addis Ababa",
  "jobType": "Full-time",
  "description": "We are looking for an experienced .NET developer to join our backend team.",
  "salary": 25000
}

###

### Delete job
DELETE {{host}}/api/jobs/1

###

### Register a new user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}