@JobPortal.Api_HostAddress = http://localhost:5263

### Get all jobs

GET {{JobPortal.Api_HostAddress}}/api/jobs

###

### Get job by ID

GET {{JobPortal.Api_HostAddress}}/api/jobs/1

###

### Get job that does not exist

GET {{JobPortal.Api_HostAddress}}/api/jobs/999

###

### Create a job

POST {{JobPortal.Api_HostAddress}}/api/jobs
Content-Type: application/json

{
  "title": "Junior .NET Developer",
  "company": "ABC Technologies",
  "location": "Addis Ababa",
  "jobType": "Full-time",
  "description": "We are looking for a junior .NET developer to join our development team.",
  "salary": 15000
}